// Mock doctor data — swap with Prisma queries when DB is live

export const MOCK_DOCTOR = {
  id: 'd-001',
  userId: 'u-002',
  name: 'Dr. Anita Sharma',
  licenseNumber: 'NMC-2019-003421',
  specialization: 'General Medicine',
  subspecialization: 'Internal Medicine',
  experienceYears: 8,
  hospital: 'Grande International Hospital',
  consultationFee: 800,
  isVerified: true,
}

export const MOCK_DOCTOR_PATIENTS = [
  {
    id: 'p-001',
    name: 'Ramesh Bahadur Thapa',
    citizenshipNumber: '02-01-70-12345',
    dateOfBirth: '1990-05-15',
    gender: 'male' as const,
    bloodType: 'A_POS',
    phone: '+977-9841234567',
    district: 'Kathmandu',
    lastVisit: '2024-11-20',
    conditions: ['Hypertension', 'Vitamin D Deficiency'],
  },
  {
    id: 'p-002',
    name: 'Sita Kumari Adhikari',
    citizenshipNumber: '02-02-75-67890',
    dateOfBirth: '1985-08-22',
    gender: 'female' as const,
    bloodType: 'B_NEG',
    phone: '+977-9812233445',
    district: 'Lalitpur',
    lastVisit: '2024-12-05',
    conditions: ['Type 2 Diabetes', 'Hypothyroidism'],
  },
  {
    id: 'p-003',
    name: 'Bikash Rai',
    citizenshipNumber: '05-01-80-11122',
    dateOfBirth: '1978-03-10',
    gender: 'male' as const,
    bloodType: 'O_POS',
    phone: '+977-9867788990',
    district: 'Bhaktapur',
    lastVisit: '2025-01-15',
    conditions: ['Asthma', 'Allergic Rhinitis'],
  },
  {
    id: 'p-004',
    name: 'Mina Tamang',
    citizenshipNumber: '03-01-92-99001',
    dateOfBirth: '1998-11-30',
    gender: 'female' as const,
    bloodType: 'AB_POS',
    phone: '+977-9845566778',
    district: 'Kathmandu',
    lastVisit: '2025-02-08',
    conditions: ['Anemia', 'PCOS'],
  },
]

export const MOCK_DOCTOR_APPOINTMENTS = [
  {
    id: 'apt-d-1',
    patientId: 'p-001',
    patientName: 'Ramesh Bahadur Thapa',
    scheduledAt: '2025-02-15T10:00:00',
    type: 'in_person' as const,
    status: 'scheduled' as const,
    reason: 'Blood pressure follow-up + lipid profile review',
    durationMinutes: 30,
  },
  {
    id: 'apt-d-2',
    patientId: 'p-002',
    patientName: 'Sita Kumari Adhikari',
    scheduledAt: '2025-02-15T10:30:00',
    type: 'in_person' as const,
    status: 'confirmed' as const,
    reason: 'Diabetes management — HbA1c results',
    durationMinutes: 30,
  },
  {
    id: 'apt-d-3',
    patientId: 'p-003',
    patientName: 'Bikash Rai',
    scheduledAt: '2025-02-15T11:30:00',
    type: 'telemedicine' as const,
    status: 'scheduled' as const,
    reason: 'Asthma controller review',
    durationMinutes: 20,
  },
  {
    id: 'apt-d-4',
    patientId: 'p-004',
    patientName: 'Mina Tamang',
    scheduledAt: '2025-02-15T14:00:00',
    type: 'in_person' as const,
    status: 'scheduled' as const,
    reason: 'New patient — irregular cycles + fatigue',
    durationMinutes: 45,
  },
]

export const MOCK_AI_DISEASE_ALERTS = [
  {
    id: 'alert-1',
    severity: 'high' as const,
    type: 'outbreak',
    title: 'Dengue Fever Surge — Kathmandu Valley',
    description: 'Case load up 340% vs same period last year. 23 ICU admissions at TU Teaching Hospital this week.',
    affected: 'Kathmandu, Lalitpur, Bhaktapur',
    action: 'Report suspected cases to District Health Office. Emphasise mosquito control to patients.',
    date: '2025-02-14',
    source: 'Epidemiology & Disease Control Division, DoHS',
  },
  {
    id: 'alert-2',
    severity: 'medium' as const,
    type: 'seasonal',
    title: 'Influenza Season — Above Baseline Activity',
    description: 'ILI sentinel surveillance shows 18% positivity rate. H3N2 dominant strain this season.',
    affected: 'All Provinces',
    action: 'Prioritise antivirals for high-risk groups. Promote vaccination for unvaccinated patients.',
    date: '2025-02-10',
    source: 'WHO Nepal & NPHL',
  },
  {
    id: 'alert-3',
    severity: 'low' as const,
    type: 'advisory',
    title: 'Antibiotic Resistance Advisory — Fluoroquinolones',
    description: 'ESBL E. coli resistance to ciprofloxacin at 67% in Kathmandu labs.',
    affected: 'Urban Centres',
    action: 'Use culture-guided therapy. Avoid empiric fluoroquinolones for UTIs without susceptibility data.',
    date: '2025-02-08',
    source: 'National Public Health Laboratory',
  },
]

export const MOCK_PATIENT_DETAIL = {
  id: 'p-001',
  name: 'Ramesh Bahadur Thapa',
  citizenshipNumber: '02-01-70-12345',
  dateOfBirth: '1990-05-15',
  gender: 'male',
  bloodType: 'A_POS',
  phone: '+977-9841234567',
  email: 'ramesh.thapa@gmail.com',
  address: 'Baneshwor, Ward No. 10, Kathmandu',
  guardianName: 'Shanti Devi Thapa',
  guardianPhone: '+977-9812345678',
  allergies: [
    { allergenName: 'Penicillin', severity: 'life_threatening', reaction: 'Anaphylaxis — severe breathing difficulty' },
    { allergenName: 'Shellfish', severity: 'moderate', reaction: 'Urticaria, nausea' },
  ],
  medicalHistory: [
    { date: '2024-11-20', title: 'Annual Checkup — Hypertension Dx', doctor: 'Dr. Anita Sharma', type: 'diagnosis' },
    { date: '2024-08-10', title: 'Hypertension Follow-up', doctor: 'Dr. Anita Sharma', type: 'visit_note' },
    { date: '2024-03-05', title: 'ECG & Cardiac Assessment', doctor: 'Dr. Rajan Karki', type: 'procedure' },
    { date: '2022-06-20', title: 'Appendectomy', doctor: 'Dr. Bijay Paudel', type: 'procedure' },
  ],
  currentMedications: ['Amlodipine 5mg OD', 'Telmisartan 40mg OD', 'Cholecalciferol 60,000 IU Weekly'],
  vitalSigns: {
    bp: '130/85 mmHg',
    hr: '74 bpm',
    temp: '36.8°C',
    weight: '72 kg',
    height: '170 cm',
    bmi: '24.9',
    spo2: '98%',
  },
  labHighlights: [
    { test: 'Lipid Profile', result: 'LDL 135 mg/dL — mildly elevated', date: '2024-11-20', isAbnormal: true },
    { test: 'Vitamin D', result: '12.5 ng/mL — deficient', date: '2024-11-20', isAbnormal: true },
    { test: 'CBC', result: 'All parameters normal', date: '2024-11-20', isAbnormal: false },
    { test: 'Fasting Glucose', result: '94 mg/dL — normal', date: '2024-08-10', isAbnormal: false },
  ],
}
